language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - 'pypy'
  - 'pypy3'
install: pip install -r build_requirements.txt
script:
  - python setup.py sdist
  - python setup.py bdist_wheel
  - flake8 multipla.py
  - coverage run test_multipla.py -v
after_success:
  - coveralls
deploy:
  provider: pypi
  user: monkeython
  password:
    secure: el+nlWhEjos4ofYJJf+FrU4H9o28bzLzsu3wW+xx8mPZHE/vY33WEniLSqI7wION+KlRXCVASa1XF25rKFp2TIybB8FlpyUZdz2gprUbX9tGy6uxjLnWS9BnkSqu3EfQRfN0p9pCwGXhJPNXYI9A8kZnaxKtNhZnkLnxjrSUaV8=
  on:
    tags: true
    all_branches: true
    repo: monkeython/multipla
    distribution: "sdist bdist_wheel"
